rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ree
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
notifications:
  recipients:
    - graf.otodrakula@gmail.com
    - ryan@railscasts.com
